export const WORDS = [
  { id: 'w001', en: "endangered species", ja: "絶滅危惧種", level: 'pre2', ex: "An endangered species is a group of animals or plants which could soon become extinct.", exja: "絶滅危惧種とは、まもなく絶滅しそうな動物や植物の一群です。" },
  { id: 'w002', en: "extinct", ja: "絶滅した", level: 'pre2', ex: "Many species are nearly extinct and could disappear from the Earth very soon.", exja: "多くの種はほとんど絶滅しかけており、まもなく地球上から消えてしまうかもしれません。" },
  { id: 'w003', en: "extinction", ja: "絶滅", level: 'pre2', ex: "Extinction happens when the last animal of the species has died out.", exja: "絶滅は、その種の最後の動物が死に絶えたときに起こります。" },
  { id: 'w004', en: "habitat destruction", ja: "生息地の破壊", level: 'pre1', ex: "Habitat destruction is the main reason why animals become endangered.", exja: "生息地の破壊が動物が絶滅危惧種になる主な理由です。" },
  { id: 'w005', en: "overfishing", ja: "乱獲", level: 'pre1', ex: "Large sea creatures have all become endangered species because of overfishing.", exja: "大型海洋生物はすべて乱獲のせいで絶滅危惧種になっています。" },
  { id: 'w006', en: "pollution", ja: "汚染", level: 'pre2', ex: "Animal habitats are also destroyed because of pollution.", exja: "動物の生息地は汚染によっても破壊されます。" },
  { id: 'w007', en: "sanctuary", ja: "保護区", level: 'pre1', ex: "Governments can provide funding for animal sanctuaries and zoos.", exja: "政府は動物保護区や動物園への資金提供ができます。" },
  { id: 'w008', en: "financial penalty", ja: "金銭的な罰", level: 'pre1', ex: "Companies who destroy animal habitats should face a financial penalty.", exja: "動物の生息地を破壊する企業は金銭的な罰を受けるべきです。" },
  { id: 'w009', en: "cooperate", ja: "協力する", level: '2', ex: "If we all cooperate by taking these steps, we will protect our planet.", exja: "もし私たち全員がこれらの対策を取ることで協力すれば、地球を守ることができます。" },
  { id: 'w010', en: "trade", ja: "取引する", level: '3', ex: "Governments can make it against the law to trade in endangered species.", exja: "政府は絶滅危惧種の取引を違法にすることができます。" },
  { id: 'w011', en: "hunting", ja: "狩猟", level: '3', ex: "Endangered species are also the result of hunting and fishing.", exja: "絶滅危惧種は狩猟や漁業の結果でもあります。" },
  { id: 'w012', en: "seal", ja: "アザラシ", level: 'pre2', ex: "Some seal species are now almost extinct because they are killed for their fur.", exja: "いくつかのアザラシの種はほとんど絶滅しかけています。" },
  { id: 'w013', en: "fur", ja: "毛皮", level: 'pre2', ex: "Some seal species are killed for their fur to make coats.", exja: "いくつかのアザラシの種はコートを作るために毛皮目的で殺されます。" },
  { id: 'w014', en: "medicine", ja: "薬", level: '3', ex: "Tigers are shot to make medicine and tea from their bones.", exja: "トラは骨から薬やお茶を作るために銃殺されます。" },
  { id: 'w015', en: "crocodile", ja: "ワニ", level: 'pre2', ex: "Crocodiles are caught to make bags and shoes.", exja: "ワニはバッグや靴を作るために捕獲されます。" },
  { id: 'w016', en: "breed", ja: "繁殖させる", level: 'pre2', ex: "These protect animals from extinction by breeding more endangered animals.", exja: "これらはより多くの絶滅危惧動物を繁殖させることで動物を絶滅から守ります。" },
  { id: 'w017', en: "release", ja: "放す、解放する", level: 'pre2', ex: "Endangered animals can later be released into the wild.", exja: "絶滅危惧動物は後に野生に放つことができます。" },
  { id: 'w018', en: "wild", ja: "野生（の）", level: '3', ex: "Endangered animals can later be released into the wild.", exja: "絶滅危惧動物は後に野生に放つことができます。" }
];
